### ISSUE TITLE
[Bug] If there is no content on the blog page, it gives a 404 error!

### ISSUE THREAD

**Issue by ramazansancar** [chesslablab/website#384]
If there is no content on the blog page, the site gives a 404 error. And you reach a dead end.

![image](https://github.com/user-attachments/assets/4f88c1a5-e027-423c-a41d-ef2d63f81545)

![image](https://github.com/user-attachments/assets/161a9333-84cd-436f-8f06-756cda2fd30b)

**Comment by programarivm** [comment]
Thank you @ramazansancar for asking this question.

Since the HTTP status code 404 means that the requested URL can't be found, it is just fine for web crawlers to get notified with it if trying to index the page. However, the message obtained is definitely not usable because there isn't anything broken because of an error. This seems to be a common issue: 

- https://github.com/nuxt-modules/i18n/issues/892
- [Setting 404 on pages with no translations](https://wpml.org/forums/topic/setting-404-on-pages-with-no-translations/)

What about customizing the 404 error page for users?

> Ziyaret etmeye çalıştığınız yayın henüz Türkçe'ye çevrilmemiştir.

Happy learning!

**Comment by ramazansancar** [comment]
Will adding this code to the relevant field solve the problem? I couldn't test it because I had some problems with Docker. @programarivm 

```php
if(!file_exists(
    self::DATA_FOLDER . '/' .
    $locale . '/' .
    basename($routes[$request->attributes->get('_route')]['path']) . '.md'
)) {
    throw $this->createNotFoundException('This post does not exist');
}
```

https://github.com/chesslablab/website/blob/0e5866ae7b08ce23ba345ee1d37969c6f4a8e3d7/src/Controller/BlogController.php#L61-L75
